version: '3'


services:

  postgres:
    image: postgres:12.3-alpine
    environment:
      - POSTGRES_PASSWORD=default
      - POSTGRES_DB=hs_data_services
    volumes:
      - data_services_volume:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  geoserver:
    image: kartoza/geoserver:2.22.0
    environment: 
      - GEOSERVER_UID=${IRODS_ACCESS_UID:-501}                                # A user ID on the host with read permissions to the iRODS directory
      - GEOSERVER_CSRF_WHITELIST=${HYDROSHARE_DOMAIN:-hydroshare.org}
      - HTTP_PORT=8080
      - HTTP_PROXY_PORT=${DATA_SERVICES_PORT:-8090}
      - HTTP_PROXY_NAME=${DATA_SERVICES_DOMAIN}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_PASSWORD:-geoserver}
      - GEOSERVER_ADMIN_USER=${GEOSERVER_USERNAME:-admin}
    volumes:
      - geoserver_volume:/var/local/geoserver
      - ./conf/geoserver/geoserver.sh:/usr/local/bin/start.sh  # Overwrite the default startup script to allow anonymous GET access
      - idata_vault_vol:/projects

  redis:
    image: redis:6.0.4-alpine

  flower:  
    image: mher/flower:0.9.5
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=8040
      - FLOWER_URL_PREFIX=flower
    depends_on:
      - redis

  gunicorn:
    build: .
    command: /usr/bin/supervisord -c /home/dsuser/conf/gunicorn/gunicorn.conf
    volumes:
      - static:/static
      - "./hs_data_services:/home/dsuser/hs_data_services"
    depends_on:
      - postgres

  celery-worker:
    build: .
    command: /usr/bin/supervisord -c /home/dsuser/conf/celery-worker/celery_worker.conf
    depends_on:
      - redis
      - postgres
    volumes:
      - "./hs_data_services:/home/dsuser/hs_data_services"

  celery-beat:
    build: .
    command: /usr/bin/supervisord -c /home/dsuser/conf/celery-beat/celery_beat.conf
    depends_on:
      - redis
      - celery-worker
      - postgres

  nginx:
    image: nginx:1.19
    ports:
      - ${DATA_SERVICES_PORT:-8090}:80                              # Expose all services locally on port
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
      - static:/static
      #- /opt/hs-certs:/opt/hs-certs                            # Used to configure SSL if available.
    depends_on:
      - gunicorn
      - geoserver
      - flower


volumes:
  idata_vault_vol:
    external: true
    name: hydroshare_idata_vault_vol
  static:
  data_services_volume:
  geoserver_volume:
