version: '3'


services:

  postgres:
    image: postgres:12.3-alpine
    environment:
      - POSTGRES_PASSWORD=default
      - POSTGRES_DB=hs_data_services
    volumes:
      - data_services_volume:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  geoserver:
    image: oscarfonts/geoserver:2.14.1
    environment: 
      - CUSTOM_UID=${IRODS_ACCESS_UID:-501}                                # A user ID on the host with read permissions to the iRODS directory
      - GEOSERVER_CSRF_WHITELIST=${HYDROSHARE_DOMAIN:-hydroshare.org}    # e.g. hydroshare.org
    volumes:
      - geoserver_volume:/var/local/geoserver
      - ./conf/geoserver/geoserver.sh:/usr/local/bin/start.sh  # Overwrite the default startup script to allow anonymous GET access
      - projects:/projects:ro                                 # Mount projects as a read-only volume to grant access to resources

  redis:
    image: redis:6.0.4-alpine

  flower:  
    image: mher/flower:0.9.5
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=8040
      - FLOWER_URL_PREFIX=flower
    depends_on:
      - redis

  gunicorn:
    build: .
    command: /usr/bin/supervisord -c /home/dsuser/conf/gunicorn/gunicorn.conf
    volumes:
      - static:/static                                        # Static files will be stored locally at root.
    depends_on:
      - postgres

  celery-worker:
    build: .
    command: /usr/bin/supervisord -c /home/dsuser/conf/celery-worker/celery_worker.conf
    depends_on:
      - redis
      - postgres

  celery-beat:
    build: .
    command: /usr/bin/supervisord -c /home/dsuser/conf/celery-beat/celery_beat.conf
    depends_on:
      - redis
      - celery-worker
      - postgres

  nginx:
    image: nginx:1.19
    ports:
      - ${DATA_SERVICES_PORT:-8090}:80                              # Expose all services locally on port
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
      - static:/static                                        # Static files will be stored locally at root.
      #- /opt/hs-certs:/opt/hs-certs                            # Used to configure SSL if available.
    depends_on:
      - gunicorn
      - geoserver
      - flower


volumes:
  projects:
  static:
  data_services_volume:
  geoserver_volume:
